infrastructure. inventory and media

diff --git a/ansible/commands/nginx-start b/ansible/commands/nginx-start
--- a/ansible/commands/nginx-start
+++ b/ansible/commands/nginx-start
@@ -1,7 +1,22 @@
 #!/bin/bash -eu
 project_root=$(cd `dirname ${BASH_SOURCE[0]}`; cd ../..; pwd)
+
+dev_mode=false
+while getopts ":d" opt; do
+    case "$opt" in
+        d) dev_mode=true;;
+        \?) echo "Invalid option -$OPTARG"; exit 1;;
+    esac
+done
+args=${@:$OPTIND}
+
+dev_volume=""
+if [ $dev_mode = true ];then
+    dev_volume="-v $project_root/code/nginx:/var/lendsnap/nginx "
+fi
+
 docker run --name nginx -t -d \
-    -v $project_root/code/nginx:/var/lendsnap/nginx \
+    $dev_volume \
     --volumes-from data-uploaded \
     -p 80:80 \
     --link db:db \
diff --git a/ansible/commands/node-tests b/ansible/commands/node-tests
--- a/ansible/commands/node-tests
+++ b/ansible/commands/node-tests
@@ -1,6 +1,21 @@
 #!/bin/bash -eu
 project_root=$(cd `dirname ${BASH_SOURCE[0]}`; cd ../..; pwd)
+
+dev_mode=false
+while getopts ":d" opt; do
+    case "$opt" in
+        d) dev_mode=true;;
+        \?) echo "Invalid option -$OPTARG"; exit 1;;
+    esac
+done
+args=${@:$OPTIND}
+
+dev_volume=""
+if [ $dev_mode = true ];then
+    dev_volume="-v $project_root/code/node:/var/lendsnap/node "
+fi
+
 docker run --name node-tests -t --rm \
-    -v $project_root/code/node:/var/lendsnap/node \
+    $dev_volume \
     --link db:db \
     node node_modules/vows/bin/vows --spec test/*-spec.js
